import os


SHORT_LINK_MAX_LENGHT = 16
SYMBOLS_CHOICE_LENGHT = 6


class Config(object):
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URI')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.getenv('SECRET_KEY')